using Content.Client.ADT.PDA;
using Content.Client.GameTicking.Managers;
using Content.Shared.MedicalScanner;
using Content.Shared.PDA;
using Robust.Shared.Utility;
using Content.Shared.CartridgeLoader;
using Content.Client.Message;
using Content.Shared.AlertLevel;
using Robust.Client.UserInterface;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;
using Robust.Shared.Timing;

namespace Content.Client.PDA
{
    [GenerateTypedNameReferences]
    public sealed partial class PdaMenu : PdaWindow
    {
        [Dependency] private IClipboardManager _clipboard = null!;
        [Dependency] private IGameTiming _gameTiming = default!;
        [Dependency] private IEntitySystemManager _entitySystem = default!;
        private readonly AlertLevelSystem _alert = default!;
        private readonly ClientGameTicker _gameTicker;

        public const int HomeView = 0;
        public const int ProgramListView = 1;
        public const int SettingsView = 2;
        public const int ProgramContentView = 3;
        public const int HealthScanViewIndex = 4; // ADT-Tweak


        private string _pdaOwner = Loc.GetString("comp-pda-ui-unknown");
        private string _owner = Loc.GetString("comp-pda-ui-unknown");
        private string _jobTitle = Loc.GetString("comp-pda-ui-unassigned");
        private string _stationName = Loc.GetString("comp-pda-ui-unknown");
        private string _alertLevel = Loc.GetString("comp-pda-ui-unknown");
        private string _instructions = Loc.GetString("comp-pda-ui-unknown");
        private string _currentDate = Loc.GetString("comp-pda-ui-unknown"); // DeltaV - PDA date


        private int _currentView;

        public event Action<EntityUid>? OnProgramItemPressed;
        public event Action<EntityUid>? OnUninstallButtonPressed;
        public event Action<EntityUid>? OnInstallButtonPressed;
        // ADT-Tweak Start
        public event Action? OnLeftMedTekView;
        public event Action<int>? OnViewChanged;

        private PdaInteriorPalette? _interiorPalette;
        // ADT-Tweak End

        public PdaMenu()
        {
            IoCManager.InjectDependencies(this);
            _alert = _entitySystem.GetEntitySystem<AlertLevelSystem>();
            _gameTicker = _entitySystem.GetEntitySystem<ClientGameTicker>();
            RobustXamlLoader.Load(this);

            ViewContainer.OnChildAdded += control => control.Visible = false;

            HomeButton.IconTexture = new SpriteSpecifier.Texture(new("/Textures/Interface/home.png"));
            FlashLightToggleButton.IconTexture = new SpriteSpecifier.Texture(new("/Textures/Interface/light.png"));
            EjectPenButton.IconTexture = new SpriteSpecifier.Texture(new("/Textures/Interface/pencil.png"));
            EjectIdButton.IconTexture = new SpriteSpecifier.Texture(new("/Textures/Interface/eject.png"));
            EjectPaiButton.IconTexture = new SpriteSpecifier.Texture(new("/Textures/Interface/pai.png"));
            ProgramCloseButton.IconTexture = new SpriteSpecifier.Texture(new("/Textures/Interface/Nano/cross.svg.png"));


            HomeButton.OnPressed += _ =>
            {
                NotifyLeftMedTek(); // ADT-Tweak
                ToHomeScreen();
            };

            ProgramListButton.OnPressed += _ =>
            {
                NotifyLeftMedTek(); // ADT-Tweak
                HomeButton.IsCurrent = false;
                ProgramListButton.IsCurrent = true;
                SettingsButton.IsCurrent = false;
                ProgramTitle.IsCurrent = false;

                ChangeView(ProgramListView);
            };


            SettingsButton.OnPressed += _ =>
            {
                NotifyLeftMedTek(); // ADT-Tweak
                HomeButton.IsCurrent = false;
                ProgramListButton.IsCurrent = false;
                SettingsButton.IsCurrent = true;
                ProgramTitle.IsCurrent = false;

                ChangeView(SettingsView);
            };

            ProgramTitle.OnPressed += _ =>
            {
                HomeButton.IsCurrent = false;
                ProgramListButton.IsCurrent = false;
                SettingsButton.IsCurrent = false;
                ProgramTitle.IsCurrent = true;

                // ADT-Tweak Start: MedTek uses the program title tab
                if (_currentView == HealthScanViewIndex)
                    return;
                // ADT-Tweak End

                ChangeView(ProgramContentView);
            };

            ProgramCloseButton.OnPressed += _ =>
            {
                NotifyLeftMedTek(); // ADT-Tweak
                HideProgramHeader();
                ToHomeScreen();
            };

            PdaOwnerButton.OnPressed += _ =>
            {
                _clipboard.SetText(_pdaOwner);
            };

            IdInfoButton.OnPressed += _ =>
            {
                _clipboard.SetText(_owner + ", " + _jobTitle);
            };

            StationNameButton.OnPressed += _ =>
            {
                _clipboard.SetText(_stationName);
            };

            StationAlertLevelButton.OnPressed += _ =>
            {
                _clipboard.SetText(_alertLevel);
            };

            StationTimeButton.OnPressed += _ =>
            {
                var stationTime = _gameTiming.CurTime.Subtract(_gameTicker.RoundStartTimeSpan);
                _clipboard.SetText((stationTime.ToString("hh\\:mm\\:ss")));
            };

            StationAlertLevelInstructionsButton.OnPressed += _ =>
            {
                _clipboard.SetText(_instructions);
            };

            // Begin DeltaV additions
            CurrentDateButton.OnPressed += _ =>
            {
                _clipboard.SetText(_currentDate);
            };
            // End DeltaV additions



            HideAllViews();
            HomeButton.IsCurrent = false;   //ADT-Tweak
        }

        public void UpdateState(PdaUpdateState state)
        {
            FlashLightToggleButton.IsActive = state.FlashlightEnabled;

            if (state.PdaOwnerInfo.ActualOwnerName != null)
            {
                _pdaOwner = state.PdaOwnerInfo.ActualOwnerName;
                PdaOwnerLabel.SetMarkup(Loc.GetString("comp-pda-ui-owner",
                    ("actualOwnerName", _pdaOwner)));
                PdaOwnerLabel.Visible = true;
            }
            else
            {
                PdaOwnerLabel.Visible = false;
            }


            if (state.PdaOwnerInfo.IdOwner != null || state.PdaOwnerInfo.JobTitle != null)
            {
                _owner = state.PdaOwnerInfo.IdOwner ?? Loc.GetString("comp-pda-ui-unknown");
                _jobTitle = state.PdaOwnerInfo.JobTitle ?? Loc.GetString("comp-pda-ui-unassigned");
                IdInfoLabel.SetMarkup(Loc.GetString("comp-pda-ui",
                    ("owner", _owner),
                    ("jobTitle", _jobTitle)));
            }
            else
            {
                IdInfoLabel.SetMarkup(Loc.GetString("comp-pda-ui-blank"));
            }

            _stationName = state.StationName ?? Loc.GetString("comp-pda-ui-unknown");
            StationNameLabel.SetMarkup(Loc.GetString("comp-pda-ui-station",
                ("station", _stationName)));


            var stationTime = _gameTiming.CurTime.Subtract(_gameTicker.RoundStartTimeSpan);

            StationTimeLabel.SetMarkup(Loc.GetString("comp-pda-ui-station-time",
                ("time", stationTime.ToString("hh\\:mm\\:ss"))));

            var alertColor = state.PdaOwnerInfo.StationAlertColor;
            (_alertLevel, _, _instructions) = _alert.AlertLevelData(state.PdaOwnerInfo.StationAlertLevel);

            StationAlertLevelLabel.SetMarkup(Loc.GetString(
                "comp-pda-ui-station-alert-level",
                ("color", alertColor),
                ("level", _alertLevel)
            ));
            StationAlertLevelInstructions.SetMarkup(Loc.GetString(
                "comp-pda-ui-station-alert-level-instructions",
                ("instructions", _instructions))
            );

            // Begin DeltaV additions
            if (state.PdaOwnerInfo.CurrentDate is { } curDate)
                _currentDate = curDate.ToString("dd MMMM yyyy");
                CurrentDateLabel.SetMarkup(Loc.GetString(
                    "comp-pda-ui-current-date",
                    ("date", _currentDate)
                ));
            // End DeltaV additions

            AddressLabel.Text = state.Address?.ToUpper() ?? " - ";

            EjectIdButton.IsActive = state.PdaOwnerInfo.IdOwner != null || state.PdaOwnerInfo.JobTitle != null;
            EjectPenButton.IsActive = state.HasPen;
            EjectPaiButton.IsActive = state.HasPai;
            ActivateMusicButton.Visible = state.CanPlayMusic;
            ShowUplinkButton.Visible = state.HasUplink;
            LockUplinkButton.Visible = state.HasUplink;
        }

        public void UpdateAvailablePrograms(List<(EntityUid, CartridgeComponent)> programs)
        {
            if (programs.Count == 0)
            {
                ProgramList.RemoveAllChildren();

                ProgramList.AddChild(new Label()
                {
                    Text = Loc.GetString("comp-pda-io-no-programs-available"),
                    HorizontalAlignment = HAlignment.Center,
                    VerticalAlignment = VAlignment.Center,
                    VerticalExpand = true,
                    FontColorOverride = _interiorPalette?.Fg ?? Color.FromHex("#1A1A1A"), // ADT-Tweak
                });

                return;
            }

            if (ProgramList.ChildCount >= 1 && ProgramList.Children[0] is Label label)
            {
                label.Orphan();
            }

            while (ProgramList.ChildCount > programs.Count)
            {
                ProgramList.Children[ProgramList.ChildCount - 1].Orphan();
            }

            for (var i = 0; i < programs.Count; i++)
            {
                var cartridge = programs[i];

                if (i < ProgramList.ChildCount)
                {
                    var currentItem = ProgramList.Children[i];
                    if (currentItem is PdaProgramItem programItem)
                    {
                        programItem.SetCartridge(cartridge);
                        continue;
                    }

                    DebugTools.Assert(i == ProgramList.ChildCount-1);
                    currentItem.Orphan();
                }

                var item = new PdaProgramItem(cartridge);
                item.OnProgramItemPressed += uid => OnProgramItemPressed?.Invoke(uid);
                item.OnUninstallButtonPressed += uid => OnUninstallButtonPressed?.Invoke(uid);
                item.OnInstallButtonPressed += uid => OnInstallButtonPressed?.Invoke(uid);
                ApplyProgramItemTheme(item);
                ProgramList.AddChild(item);
            }
        }

        /// <summary>
        /// Changes the current view to the home screen (view 0) and sets the tabs `IsCurrent` flag accordingly
        /// </summary>
        public void ToHomeScreen()
        {
            HomeButton.IsCurrent = true;
            ProgramListButton.IsCurrent = false;
            SettingsButton.IsCurrent = false;
            ProgramTitle.IsCurrent = false;

            ChangeView(HomeView);
        }

        /// <summary>
        /// Hides the program title and close button.
        /// </summary>
        public void HideProgramHeader()
        {
            ProgramTitle.IsCurrent = false;
            ProgramTitle.Visible = false;
            ProgramCloseButton.Visible = false;
            ProgramListButton.Visible = true;
            SettingsButton.Visible = true;
        }

        /// <summary>
        /// Changes the current view to the program content view (view 3), sets the program title and sets the tabs `IsCurrent` flag accordingly
        /// </summary>
        public void ToProgramView(string title)
        {
            HomeButton.IsCurrent = false;
            ProgramListButton.IsCurrent = false;
            SettingsButton.IsCurrent = false;
            ProgramTitle.IsCurrent = false;
            ProgramTitle.IsCurrent = true;
            ProgramTitle.Visible = true;
            ProgramCloseButton.Visible = true;
            ProgramListButton.Visible = false;
            SettingsButton.Visible = false;

            ProgramTitle.LabelText = title;
            ChangeView(ProgramContentView);
        }

        // ADT-Tweak start
        public bool IsOnHealthScanView => _currentView == HealthScanViewIndex;
        public int CurrentView => _currentView;

        private void NotifyLeftMedTek()
        {
            if (_currentView == HealthScanViewIndex)
                OnLeftMedTekView?.Invoke();
        }

        /// Updates MedTek contents without changing the current PDA view.
        public void UpdateHealthScanData(HealthAnalyzerUiState state)
        {
            HealthScanView.Populate(state);
        }

        /// Shows built-in health analyzer data inside the PDA instead of a separate window.
        public void ShowHealthScan(HealthAnalyzerUiState state)
        {
            HealthScanView.Populate(state);

            if (_currentView == HealthScanViewIndex)
                return;

            HomeButton.IsCurrent = false;
            ProgramListButton.IsCurrent = false;
            SettingsButton.IsCurrent = false;
            ProgramTitle.IsCurrent = true;
            ProgramTitle.Visible = true;
            ProgramCloseButton.Visible = true;
            ProgramListButton.Visible = false;
            SettingsButton.Visible = false;
            ProgramTitle.LabelText = Loc.GetString("comp-pda-ui-health-scan-title");
            ChangeView(HealthScanViewIndex);
        }

        /// Restores a non-MedTek view before the PDA becomes visible again.
        public void RestoreView(int view)
        {
            if (view is < HomeView or > ProgramContentView)
                view = HomeView;

            switch (view)
            {
                case HomeView:
                    HideProgramHeader();
                    ToHomeScreen();
                    break;
                case ProgramListView:
                    HomeButton.IsCurrent = false;
                    ProgramListButton.IsCurrent = true;
                    SettingsButton.IsCurrent = false;
                    ProgramTitle.IsCurrent = false;
                    ChangeView(ProgramListView);
                    break;
                case SettingsView:
                    HomeButton.IsCurrent = false;
                    ProgramListButton.IsCurrent = false;
                    SettingsButton.IsCurrent = true;
                    ProgramTitle.IsCurrent = false;
                    ChangeView(SettingsView);
                    break;
                case ProgramContentView:
                    HomeButton.IsCurrent = false;
                    ProgramListButton.IsCurrent = false;
                    SettingsButton.IsCurrent = false;
                    ProgramTitle.IsCurrent = true;
                    ProgramTitle.Visible = true;
                    ProgramCloseButton.Visible = true;
                    ProgramListButton.Visible = false;
                    SettingsButton.Visible = false;
                    ChangeView(ProgramContentView);
                    break;
            }
        }

        public void ApplyHealthScanDividerColor(Color color)
        {
            HealthScanView.ApplyDividerColor(color);
        }

        /// Paints everything inside the PDA content frame from the secondary accent.
        public void ApplyInteriorTheme(Color secondary, Color _)
        {
            var palette = PdaInteriorTheme.FromSecondary(secondary);
            _interiorPalette = palette;

            ApplyMonitorTheme(palette);

            foreach (var child in NavigationBar.Children)
            {
                if (child is not PdaNavigationButton nav)
                    continue;

                var wasCurrent = nav.IsCurrent;
                var wasActive = nav.IsActive;
                nav.InactiveBgColor = palette.NavInactive.ToHex();
                nav.ActiveBgColor = palette.NavActive.ToHex();
                nav.InactiveFgColor = palette.FgMuted.ToHex();
                if (nav != FlashLightToggleButton)
                    nav.ActiveFgColor = palette.Fg.ToHex();
                else
                    nav.ActiveFgColor = "#EAEFBB";

                nav.IsCurrent = wasCurrent;
                nav.IsActive = wasActive;
                nav.SetBorderColor(palette.NavBorder);
            }

            ApplySettingsButtonTheme(AccessRingtoneButton, palette);
            ApplySettingsButtonTheme(ActivateMusicButton, palette);
            ApplySettingsButtonTheme(ShowUplinkButton, palette);
            ApplySettingsButtonTheme(LockUplinkButton, palette);

            OsLabel.FontColorOverride = palette.FooterFg;
            ProductLabel.FontColorOverride = palette.FooterFg;
            AddressLabel.FontColorOverride = palette.FooterFg;
            ContentFooterPanel.PanelOverride = null;
            FooterStripe.ModulateSelfOverride = palette.FooterStripe;
            NavAccentLine.PanelOverride = new StyleBoxFlat { BackgroundColor = palette.Divider };

            ApplyHealthScanDividerColor(palette.Divider);
            HealthScanView.ApplyMonitorTextTheme(palette.Fg);

            foreach (var child in ProgramList.Children)
            {
                if (child is PdaProgramItem item)
                    ApplyProgramItemTheme(item);
                else if (child is Label emptyLabel)
                    emptyLabel.FontColorOverride = palette.Fg;
            }

            ThemeProgramView();
        }

        /// Re-applies the interior palette to the active cartridge UI.
        public void ThemeProgramView()
        {
            if (_interiorPalette is not { } palette)
                return;

            foreach (var child in ProgramView.Children)
                PdaInteriorTheme.ApplyTo(child, palette);
        }

        private void ApplyProgramItemTheme(PdaProgramItem item)
        {
            if (_interiorPalette is not { } palette)
                return;

            item.ThemeNormalBg = palette.ItemBg;
            item.ThemeHoverBg = palette.ItemHover;
            item.ThemeFg = palette.Fg;
            item.InstallButton.ModulateSelfOverride = palette.ItemHover;
        }

        private static void ApplySettingsButtonTheme(PdaSettingsButton button, in PdaInteriorPalette palette)
        {
            button.ThemeNormalBg = palette.ItemBg;
            button.ThemeHoverBg = palette.ItemHover;
            button.ThemeFg = palette.Fg;
            button.ThemeDisabledFg = palette.FgMuted;
        }
        // ADT-Tweak end

        /// <summary>
        /// Changes the current view to the given view number
        /// </summary>
        public void ChangeView(int view)
        {
            if (ViewContainer.ChildCount <= view)
                return;

            ViewContainer.GetChild(_currentView).Visible = false;
            ViewContainer.GetChild(view).Visible = true;
            _currentView = view;
            OnViewChanged?.Invoke(view);    //ADT-Tweak
        }

        private void HideAllViews()
        {
            var views = ViewContainer.Children;
            foreach (var view in views)
            {
                view.Visible = false;
            }
        }

        protected override void Draw(DrawingHandleScreen handle)
        {
            base.Draw(handle);

            var stationTime = _gameTiming.CurTime.Subtract(_gameTicker.RoundStartTimeSpan);

            StationTimeLabel.SetMarkup(Loc.GetString("comp-pda-ui-station-time",
                ("time", stationTime.ToString("hh\\:mm\\:ss"))));
        }
    }
}
